//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group8_iCLOTHINGApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPassword
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPassword()
        {
            this.UserComments = new HashSet<UserComments>();
        }
    
        public int userID { get; set; }
        public string userAccountName { get; set; }
        public string userEncryptedPassword { get; set; }
        public int passwordExpiryTime { get; set; }
        public System.DateTime userAccountExpiryDate { get; set; }
    
        public virtual Customer Customer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserComments> UserComments { get; set; }
    }
}
